name: AnalystForecast
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - jupyterlab
  - ca-certificates
  - openssl
  - pip:
      eikon
prefix: C:\Users\alexa\mambaforge\envs\AnalystForecast
